EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
MIDI_ENABLE = yes


STENO_ENABLE = no
KEY_LOCK_ENABLE = no

UNICODE_ENABLE = no
UNICODEMAP_ENABLE = no

COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
API_SYSEX_ENABLE = no

AUDIO_ENABLE = no
FAUXCLICKY_ENABLE = no

RGBLIGHT_ENABLE = no
BACKLIGHT_ENABLE = no
SLEEP_LED_ENABLE = no
BLUETOOTH_ENABLE = no